export const images: string[] = [
  "/uploads/media/hotel/image_001.jpg",
  "/uploads/media/hotel/image_005.jpg",
  "/uploads/media/hotel/image_006.jpg",
  "/uploads/media/hotel/image_007.jpg",
  "/uploads/media/hotel/image_008.jpg",
  "/uploads/media/hotel/image_011.jpg",
  "/uploads/media/hotel/image_012.jpg",
  "/uploads/media/hotel/image_013.jpg",
  "/uploads/media/hotel/image_014.jpg",
  "/uploads/media/hotel/image_017.jpg",
  "/uploads/media/hotel/image_018.jpg",
  "/uploads/media/hotel/image_019.jpg",
  "/uploads/media/hotel/image_020.jpg",
  "/uploads/media/hotel/image_021.jpg",
  "/uploads/media/hotel/image_022.jpg",
  "/uploads/media/hotel/image_023.jpg",
  "/uploads/media/hotel/image_024.jpg",
  "/uploads/media/hotel/image_025.jpg",
  "/uploads/media/hotel/image_026.jpg",
  "/uploads/media/hotel/image_027.jpg",
  "/uploads/media/hotel/image_028.jpg",
  "/uploads/media/hotel/image_029.jpg",
  "/uploads/media/hotel/image_030.jpg",
  "/uploads/media/hotel/image_031.jpg",
  "/uploads/media/hotel/image_032.jpg",
  "/uploads/media/hotel/image_033.jpg",
  "/uploads/media/hotel/image_034.jpg",
  "/uploads/media/hotel/image_035.jpg",
  "/uploads/media/hotel/image_036.jpg",
  "/uploads/media/hotel/image_037.jpg",
  "/uploads/media/hotel/image_038.jpg",
  "/uploads/media/hotel/image_039.jpg",
  "/uploads/media/hotel/image_040.jpg",
  "/uploads/media/hotel/image_041.jpg",
  "/uploads/media/hotel/image_042.jpg",
  "/uploads/media/hotel/image_043.jpg",
  "/uploads/media/hotel/image_044.jpg",
  "/uploads/media/hotel/image_045.jpg",
  "/uploads/media/hotel/image_046.jpg",
  "/uploads/media/hotel/image_047.jpg",
  "/uploads/media/hotel/image_048.jpg",
  "/uploads/media/hotel/image_049.jpg",
  "/uploads/media/hotel/image_050.jpg",
  "/uploads/media/hotel/image_051.jpg",
  "/uploads/media/hotel/image_052.jpg",
  "/uploads/media/hotel/image_053.jpg",
  "/uploads/media/hotel/image_054.jpg",
  "/uploads/media/hotel/image_055.jpg",
  "/uploads/media/hotel/image_056.jpg",
  "/uploads/media/hotel/image_057.jpg",
  "/uploads/media/hotel/image_058.jpg",
  "/uploads/media/hotel/image_059.jpg",
  "/uploads/media/hotel/image_060.jpg",
  "/uploads/media/hotel/image_061.jpg",
  "/uploads/media/hotel/image_062.jpg",
  "/uploads/media/hotel/image_063.jpg",
  "/uploads/media/hotel/image_064.jpg",
  "/uploads/media/hotel/image_065.jpg",
  "/uploads/media/hotel/image_066.jpg",
  "/uploads/media/hotel/image_067.jpg",
  "/uploads/media/hotel/image_068.jpg",
  "/uploads/media/hotel/image_069.jpg",
  "/uploads/media/hotel/image_070.jpg",
  "/uploads/media/hotel/image_071.jpg",
  "/uploads/media/hotel/image_072.jpg",
  "/uploads/media/hotel/image_073.jpg",
  "/uploads/media/hotel/image_074.jpg",
  "/uploads/media/hotel/image_075.jpg",
  "/uploads/media/hotel/image_076.jpg",
  "/uploads/media/hotel/image_077.jpg",
  "/uploads/media/hotel/image_078.jpg",
  "/uploads/media/hotel/image_079.jpg",
  "/uploads/media/hotel/image_080.jpg",
  "/uploads/media/hotel/image_081.jpg",
  "/uploads/media/hotel/image_082.jpg",
  "/uploads/media/hotel/image_083.jpg",
  "/uploads/media/hotel/image_084.jpg",
  "/uploads/media/hotel/image_085.jpg",
  "/uploads/media/hotel/image_086.jpg",
  "/uploads/media/hotel/image_087.jpg",
  "/uploads/media/hotel/image_088.jpg"
];

export const roomImages = {
  single: "/uploads/media/hotel/image_001.jpg",
  double: "/uploads/media/hotel/image_005.jpg",
  twin: "/uploads/media/hotel/image_006.jpg",
  family: "/uploads/media/hotel/image_007.jpg",
  suite: "/uploads/media/hotel/image_008.jpg"
};

export const hotelImages = {
  exterior: "/uploads/media/hotel/image_011.jpg",
  lobby: "/uploads/media/hotel/image_012.jpg",
  restaurant: "/uploads/media/hotel/image_013.jpg"
};